"""add account_context

Revision ID: d2d84b9280cc
Revises: 1f862e7062ab
Create Date: 2026-07-19 14:47:56.785922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d84b9280cc'
down_revision: Union[str, Sequence[str], None] = '1f862e7062ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_yandex_accounts', sa.Column('account_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_yandex_accounts', 'account_context')
    # ### end Alembic commands ###
